[behave]
# Formatos de saída dos relatórios
format = json
         pretty

# Arquivos de saída dos relatórios
outfiles = reports/relatorio.json
           reports/relatorio.txt

# Caminho das features
paths = features

# Mostra saída do print() durante execução
show_skipped = false
